### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a link to get your app on F-Droid 👍 

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Comment by Mstrodl** [comment]
Oh! I've been waiting for this to become available on F-Droid! Thanks!

**Comment by Mstrodl** [comment]
Could you update your commit message with something more descriptive like this: `readme: add f-droid link`?

**Comment by Poussinou** [comment]
I'm not sure I can change the commit description easily via github.com

Just cherry-pick the changes, it'll be ok

**Comment by Mstrodl** [comment]
Thank you! 7f4517f48c88363dc4956ac6e842078c649a2c0d

**Pull request closed without merging**
